---
title: "New questions"
author: "Josh Hagedorn" 
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    theme:
      version: 5
      bootswatch: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(tidyverse)
tmi <- read_csv("https://raw.githubusercontent.com/j-hagedorn/trilogy/d57c2cefd0b216c8ce5c251f618c3e931c732d0a/data/tmi.csv")
atu_df <- read_csv("https://raw.githubusercontent.com/j-hagedorn/trilogy/d57c2cefd0b216c8ce5c251f618c3e931c732d0a/data/atu_df.csv")
atu_seq <- read_csv("https://raw.githubusercontent.com/j-hagedorn/trilogy/d57c2cefd0b216c8ce5c251f618c3e931c732d0a/data/atu_seq.csv")
aft <- read_csv("https://raw.githubusercontent.com/j-hagedorn/trilogy/d57c2cefd0b216c8ce5c251f618c3e931c732d0a/data/aft.csv")
```


Tales involving stepmother
Tales involving singing and dancing

Tales involving mother or queen
Tales involving son or prince
Relationship between mother/queen or son/prince

Female hero/heroine, saving community

Hero performing trickery

Different types of lacks


```{r}
regexes <- list()

regexes$lack <- "want|wish|desire|need"

lacks <-
  tmi %>%
  filter(str_detect(motif_name,regex(regexes$lack, ignore_case = T)))

```



















